import { Category } from './categorizeEngine.js';

const categoryGroups: Record<Category, string[]> = {
    'Dagligvare': [
        'extra',
        'kiwi',
        'rema',
        'coop',
        'bunnpris',
        'spar',
        'joker',
        'matkroken',
        'cc mat',
        'mix',
        'vinmonopolet',
        'obs',
        'snarkjøp',
        'lidl',
    ],
    'Mat ute': [
        'burger king',
        "mcdonald's",
        'little eat',
        'fly chicken',
        'expressenpizza',
        'pizzabakeren',
        'raufoss pizza',
        'dos amigos',
        'sander asia mat',
        'gelatiamo',
        'thai bahn',
        'wolt',
        'foodora',
        'cafe amsterdam',
        'hygge gjøvik',
        'javel oslo',
        'totensnacks',
        'king kebap',
        'selecta',
        'øya maritim',
        'max burgers',
        'dominos pizza',
        'nebbenes kro',
        'shell',
        '7-eleven',
        '7 eleven',
        'esso',
        'st1',
        'kitch',
        'salt og pepper',
        'salt & pepper',
        'waffle',
        'circle',
        'deli',
        'astral',
        'bkh',
    ],
    'Hjem': [
        'ikea',
        'søstrene grene',
        'biltema',
        'rusta',
        'jula',
        'clas ohl',
        'plantasjen',
        'kid interiør',
        'europris',
        'normal',
        'buddy',
        'musti',
        'jysk',
        'nille',
        'sport 1',
        'zoo',
        'hage',
        'elkjøp',
        'elkjop',
        'power',
        'bente',
        'ark',
        'ideal',
        'sostrene',
        'søstrene',
        'feel',
    ],
    'Underholdning': [
        'gjøvik kino',
        'norsk tipping',
        'totenbadet',
        'fjellhallen',
        'geekevents',
        'sveve',
        'fun padel',
        'padel-senter',
        'mjøsstranda',
        'tikkio',
        'kultur',
        'sound',
        '4sound',
        'maire',
        'garnius',
        'liten',
    ],
    'Gaming': ['steam', 'steam games', 'discord', 'riotgames', 'riot', 'jagex', 'eneba'],
    'Abonnement': [
        'apple',
        'tidalmusic',
        'telenor',
        'google one',
        'splice',
        'claude.ai',
        'anthropic',
        'openai',
        'scrimba',
        'real debrid',
        'suno',
        'elitehosting',
        'agderposten',
        'lyse tele',
        'lennardigi',
        'native ins',
        'netflix',
        'disney plus',
        'storytel',
        'mova as',
    ],
    'Netthandel': [
        'cdon',
        'maxgaming',
        'proshop',
        'helthjem',
        'thomann',
        'xxl',
        'norli',
        'nox padel',
        'matchi',
        'posten norge',
        'sp nox',
    ],
    'Helse': [
        'spesialistsenter',
        'apotek',
        'legevakt',
        'helfo',
        'rtg.polikl',
        'vitus',
        'legesenter',
        'oslo storbylege',
        'farmasiet',
        'evidensia',
        'specsave',
        'sunkost',
    ],
    'Kosmetikk': [
        'cutters',
        'blivakker',
        'nailster',
        'nordicnails',
        'nordicfeel',
        'kicks',
        'rituals',
        'feel raufoss',
        'zalando',
        'bubbleroom',
        'change lingerie',
        'lyko',
        'gina',
        'kappahl',
        'cosmetic',
        'euro sko',
        'makeup',
        'cubus',
        'vero',
        'atelièr',
        'get inspired',
        'nakd',
        'glitter',
        'skoringen',
        'vita',
        'silver',
        'change',
        'fredrik',
        'junkyard',
    ],
    'Kreditt': ['klarna', 'qliro', 'credicare', 'tfbank', 'riverty', 'arvato'],
    'Transport': ['ruter', 'entur', 'seaways', 'vy app', 'asfinag', 'scandlines'],
    'Bil': [
        'uno-x',
        'tesla',
        'ionity',
        'kople',
        'recharge',
        'easypark',
        'onepark',
        'apcoa',
        'nordea finans',
        'naf',
        'thansen',
        'konzum',
        'oeresund',
        'mer',
        'norges automobil',
    ],
    'Bolig': ['nedbetaling'],
    'Boutgifter': [
        'fortum',
        'vestre toten kommune',
        'ringsaker kommune',
        'globalconnect',
        'verisure',
        'omkostninger',
        'minel',
    ],
    'Forsikring': ['fremtind forsikring', 'gjensidige', 'agria'],
    'Overføring': ['betaling', 'overføring', 'kontoregulering', 'revolut', 'adyen', 'vipps'],
    'Inntekt': ['nav', 'skatteetaten', 'lønn', 'ztl payment', 'lena og centrum'],
    'Sparing': ['renter', 'dnb aksje', 'verdipapir'],
    'Diverse': ['barnas hus', 'tugo', 'stian'],
    'Annet': [],
};

export const categoryDict: Map<string, Category> = new Map(
    Object.entries(categoryGroups).flatMap(([category, keywords]) =>
        keywords.map((k) => [k, category as Category]),
    ),
);
