import { Category } from './categorizeEngine.ts';

export const categoryDict: Record<string, Category> = {
    // Dagligvare
    'extra': 'Dagligvare',
    'kiwi': 'Dagligvare',
    'rema': 'Dagligvare',
    'coop': 'Dagligvare',
    'bunnpris': 'Dagligvare',
    'spar': 'Dagligvare',
    'joker': 'Dagligvare',
    'matkroken': 'Dagligvare',
    'cc mat': 'Dagligvare',
    'mix': 'Dagligvare',
    'vinmonopolet': 'Dagligvare',
    'obs': 'Dagligvare',
    'snarkjøp': 'Dagligvare',
    'lidl': 'Dagligvare',

    // Mat ute
    'burger king': 'Mat ute',
    "mcdonald's": 'Mat ute',
    'little eat': 'Mat ute',
    'fly chicken': 'Mat ute',
    'expressenpizza': 'Mat ute',
    'pizzabakeren': 'Mat ute',
    'raufoss pizza': 'Mat ute',
    'dos amigos': 'Mat ute',
    'sander asia mat': 'Mat ute',
    'gelatiamo': 'Mat ute',
    'thai bahn': 'Mat ute',
    'wolt': 'Mat ute',
    'foodora': 'Mat ute',
    'cafe amsterdam': 'Mat ute',
    'hygge gjøvik': 'Mat ute',
    'javel oslo': 'Mat ute',
    'totensnacks': 'Mat ute',
    'king kebap': 'Mat ute',
    'selecta': 'Mat ute',
    'øya maritim': 'Mat ute',
    'max burgers': 'Mat ute',
    'dominos pizza': 'Mat ute',
    'nebbenes kro': 'Mat ute',
    'shell': 'Mat ute',
    '7-eleven': 'Mat ute',
    '7 eleven': 'Mat ute',
    'esso': 'Mat ute',
    'st1': 'Mat ute',
    'kitch': 'Mat ute',
    'salt og pepper': 'Mat ute',
    'salt & pepper': 'Mat ute',
    'waffle': 'Mat ute',
    'circle': 'Mat ute',
    'deli': 'Mat ute',
    'astral': 'Mat ute',
    'bkh': 'Mat ute',

    // Hjem
    'ikea': 'Hjem',
    'søstrene grene': 'Hjem',
    'biltema': 'Hjem',
    'rusta': 'Hjem',
    'jula': 'Hjem',
    'clas ohl': 'Hjem',
    'plantasjen': 'Hjem',
    'kid': 'Hjem',
    'europris': 'Hjem',
    'normal': 'Hjem',
    'buddy': 'Hjem',
    'musti': 'Hjem',
    'jysk': 'Hjem',
    'nille': 'Hjem',
    'sport 1': 'Hjem',
    'zoo': 'Hjem',
    'hage': 'Hjem',
    'elkjøp': 'Hjem',
    'elkjop': 'Hjem',
    'power': 'Hjem',
    'bente': 'Hjem',
    'ark': 'Hjem',
    'ideal': 'Hjem',
    'sostrene': 'Hjem',
    'søstrene': 'Hjem',
    'feel': 'Hjem',

    // Underholdning
    'gjøvik kino': 'Underholdning',
    'norsk tipping': 'Underholdning',
    'totenbadet': 'Underholdning',
    'fjellhallen': 'Underholdning',
    'geekevents': 'Underholdning',
    'sveve': 'Underholdning',
    'fun padel': 'Underholdning',
    'padel-senter': 'Underholdning',
    'mjøsstranda': 'Underholdning',
    'tikkio': 'Underholdning',
    'kultur': 'Underholdning',
    'sound': 'Underholdning',
    '4sound': 'Underholdning',
    'maire': 'Underholdning',
    'garnius': 'Underholdning',
    'liten': 'Underholdning',

    // Gaming
    'steam': 'Gaming',
    'discord': 'Gaming',
    'riotgames': 'Gaming',
    'riot': 'Gaming',
    'jagex': 'Gaming',
    'eneba': 'Gaming',

    // Abonnement
    'apple': 'Abonnement',
    'tidalmusic': 'Abonnement',
    'telenor': 'Abonnement',
    'google one': 'Abonnement',
    'splice': 'Abonnement',
    'claude.ai': 'Abonnement',
    'anthropic': 'Abonnement',
    'openai': 'Abonnement',
    'scrimba': 'Abonnement',
    'real debrid': 'Abonnement',
    'suno': 'Abonnement',
    'elitehosting': 'Abonnement',
    'agderposten': 'Abonnement',
    'lyse tele': 'Abonnement',
    'lennardigi': 'Abonnement',
    'native ins': 'Abonnement',
    'netflix': 'Abonnement',
    'disney plus': 'Abonnement',
    'storytel': 'Abonnement',
    'mova as': 'Abonnement',

    // Netthandel
    'cdon': 'Netthandel',
    'maxgaming': 'Netthandel',
    'junkyard': 'Netthandel',
    'proshop': 'Netthandel',
    'helthjem': 'Netthandel',
    'thomann': 'Netthandel',
    'xxl': 'Netthandel',
    'norli': 'Netthandel',
    'nox padel': 'Netthandel',
    'matchi': 'Netthandel',
    'posten norge': 'Netthandel',
    'sp nox': 'Netthandel',

    // Helse
    'spesialistsenter': 'Helse',
    'apotek': 'Helse',
    'legevakt': 'Helse',
    'helfo': 'Helse',
    'rtg.polikl': 'Helse',
    'vitus': 'Helse',
    'legesenter': 'Helse',
    'oslo storbylege': 'Helse',
    'farmasiet': 'Helse',
    'evidensia': 'Helse',
    'specsave': 'Helse',
    'sunkost': 'Helse',

    // Kosmetikk
    'cutters': 'Kosmetikk',
    'blivakker': 'Kosmetikk',
    'nailster': 'Kosmetikk',
    'nordicnails': 'Kosmetikk',
    'nordicfeel': 'Kosmetikk',
    'kicks': 'Kosmetikk',
    'rituals': 'Kosmetikk',
    'feel raufoss': 'Kosmetikk',
    'zalando': 'Kosmetikk',
    'bubbleroom': 'Kosmetikk',
    'change lingerie': 'Kosmetikk',
    'lyko': 'Kosmetikk',
    'gina': 'Kosmetikk',
    'kappahl': 'Kosmetikk',
    'cosmetic': 'Kosmetikk',
    'euro sko': 'Kosmetikk',
    'makeup': 'Kosmetikk',
    'cubus': 'Kosmetikk',
    'vero': 'Kosmetikk',
    'atelièr': 'Kosmetikk',
    'get inspired': 'Kosmetikk',
    'nakd': 'Kosmetikk',
    'glitter': 'Kosmetikk',
    'skoringen': 'Kosmetikk',
    'vita': 'Kosmetikk',
    'silver': 'Kosmetikk',
    'change': 'Kosmetikk',
    'fredrik': 'Kosmetikk',

    // Kreditt
    'klarna': 'Kreditt',
    'qliro': 'Kreditt',
    'credicare': 'Kreditt',
    'tfbank': 'Kreditt',
    'riverty': 'Kreditt',
    'arvato': 'Kreditt',

    // Transport
    'ruter': 'Transport',
    'entur': 'Transport',
    'seaways': 'Transport',
    'vy app': 'Transport',
    'asfinag': 'Transport',
    'scandlines': 'Transport',

    // Bil
    'uno-x': 'Bil',
    'tesla': 'Bil',
    'ionity': 'Bil',
    'kople': 'Bil',
    'recharge': 'Bil',
    'easypark': 'Bil',
    'onepark': 'Bil',
    'apcoa': 'Bil',
    'nordea finans': 'Bil',
    'naf': 'Bil',
    'thansen': 'Bil',
    'konzum': 'Bil',
    'oeresund': 'Bil',
    'mer': 'Bil',
    'norges automobil': 'Bil',

    // Bolig
    'nedbetaling': 'Bolig',

    // Boutgifter
    'fortum': 'Boutgifter',
    'vestre toten kommune': 'Boutgifter',
    'ringsaker kommune': 'Boutgifter',
    'globalconnect': 'Boutgifter',
    'verisure': 'Boutgifter',
    'omkostninger': 'Boutgifter',
    'minel': 'Boutgifter',

    // Forsikring
    'fremtind forsikring': 'Forsikring',
    'gjensidige': 'Forsikring',
    'agria': 'Forsikring',

    // Overføring
    'betaling': 'Overføring',
    'overføring': 'Overføring',
    'kontoregulering': 'Overføring',
    'revolut': 'Overføring',
    'adyen': 'Overføring',
    'vipps': 'Overføring',

    // Inntekt
    'nav': 'Inntekt',
    'skatteetaten': 'Inntekt',
    'lønn': 'Inntekt',
    'ztl payment': 'Inntekt',
    'lena og centrum': 'Inntekt',

    // Sparing
    'renter': 'Sparing',
    'dnb aksje': 'Sparing',
    'verdipapir': 'Sparing',

    // Diverse
    'barnas hus': 'Diverse',
    'tugo': 'Diverse',
    'stian': 'Diverse',
};
