import { Category } from './categories.js';
import { Options } from './types.js';

export const defaultCorporateSuffixPattern: RegExp =
    /\s+(forsikring(saktiebolaget)?|finans|norge|as|asa)\b.*$/i;

export const defaultCityPrefixes: string[] = [
    'Gjøvik',
    'Raufoss',
    'Lena',
    'Bøverbru',
    'Kapp',
    'Kolbu',
    'Reinsvoll',
    'Moelv',
    'Heidal',
    'Oslo',
];

export const defaultNWordMerchants: Record<string, number> = {
    // 2-word merchants
    'Burger': 2,
    'Mr': 2,
    'New': 2,
    'The': 2,
    'King': 2,
    'Cc': 2,
    'Supermarket': 2,
    'Crown': 2,
    'Caffe': 2,
    'Cafe': 2,
    'Hotel': 2,
    'Aashaug': 2,
    'Gina': 2,
    'Espresso': 2,
    'Apotek': 2,
    'Circle': 2,
    'Sostrene': 2,
    'Søstrene': 2,
    'Clas': 2,
    'Liten': 2,
    'Øya': 2,
    'Euro': 2,
    'Barnas': 2,
    'Get': 2,
    'Makeup': 2,
    'Vero': 2,
    'Coop': 2,
    'Bentes': 2,
    'Bente': 2,
    'EBILLETT': 2,
    'Mc': 2,
    'Change': 2,
    'Waffle': 2,
    'Little': 2,
    'Dos': 2,
    'Real': 2,
    'Fly': 2,
    'Norsk': 2,
    'Beach': 2,
    'Total': 2,
    'Frøken': 2,
    'Mv': 2,
    'Q': 2,
    'Claire': 2,

    // 3-word merchants
    'Salt': 3,
    'Deli': 3,
    'Sp ': 3,
    'Hage': 3,
};

export const defaultMerchantAliases: Record<string, string> = {
    'extra': 'Coop Extra',
    'f™rsžkringsaktiebolaget agria': 'Agria',
    'silogata': 'Ukjent',
    'mdc': "McDonald's",
    'mcdonalds': "McDonald's",
    'mcd': "McDonald's",
    "mc donald's": "McDonald's",
    'mc donald': "McDonald's",
    'lyko.com/no': 'Lyko',
    'apple.com/bill': 'Apple',
    'bk': 'Burger King',
    'tqsr': 'Burger King',
    'ossg': 'Gjøvik Poliklinikk',
    'no0770': 'H&M',
    'berit': 'Kjolesenteret Lillo',
    'rema': 'REMA 1000',
    'uno-x': 'Uno-X',
    'steamgames.com': 'Steam',
    'clas ohl': 'Clas Ohlson',
    'bkh': 'Bislett Kebab House',
    'sostrene grene': 'Søstrene Grene',
    'dfdsseaways.dk': 'DFDS',
    'caiacosmetics.no': 'Caia Cosmetics',
    'www.silverlines.no': 'Silverlines',
    'garnius.no': 'Garnius',
    'specsave': 'Specsavers',
    'sound': '4Sound',
    'bente': 'Bentes Hjerte',
    'the conjuring': 'Kino',
    'telenor': 'Telenor',
    'tfbank': 'Avarda',
    "tugo'": 'Tugo',
    'kfc': 'KFC',
    'sander': 'Sander Asia Mat',
    'vinmonopolet.no': 'Vinmonopolet',
    'hm': 'H&M',
    'aashaug blomst': 'Aashaug Blomster',
    'snap': 'Snapchat',
    'domino': 'Dominos',
    'q:blush': 'Q Blush',
    'vidaxlno': 'Vida XL',
};

export const defaultCategoryKeywords: Record<Category, string[]> = {
    'Dagligvare': [
        'extra',
        'kiwi',
        'rema',
        'coop',
        'bunnpris',
        'spar',
        'interspar',
        'supermarket',
        'joker',
        'matkroken',
        'cc mat',
        'mix',
        'vinmonopolet',
        'obs',
        'snarkjøp',
        'lidl',
        'ica',
        'maximat',
        'systembolaget',
        'gottebiten',
        'kaufland',
        'godishuset',
        'plodine',
    ],
    'Mat ute': [
        'ysteri',
        'burger king',
        "mcdonald's",
        'little eat',
        'fly chicken',
        'expressenpizza',
        'pizzabakeren',
        'raufoss pizza',
        'dos amigos',
        'sander asia mat',
        'gelatiamo',
        'thai bahn',
        'wolt',
        'foodora',
        'cafe amsterdam',
        'hygge gjøvik',
        'javel oslo',
        'totensnacks',
        'king kebap',
        'selecta',
        'øya maritim',
        'max burgers',
        'dominos pizza',
        'nebbenes kro',
        'shell',
        '7-eleven',
        '7 eleven',
        'esso',
        'st1',
        'kitch',
        'salt og pepper',
        'salt & pepper',
        'waffle',
        'circle',
        'deli',
        'astral',
        'bkh',
        'slasticarna',
        'fly chicken',
        'tqsr',
        'caffe',
        'yx',
        'bakeri',
        'konoba',
        'kfc',
        'heim',
        'heidi',
        'dominos',
        'olearys',
    ],
    'Hjem': [
        'interhome',
        'vidaxl',
        'ikea',
        'søstrene grene',
        'biltema',
        'rusta',
        'jula',
        'plantasjen',
        'kid interiør',
        'europris',
        'normal',
        'buddy',
        'musti',
        'jysk',
        'nille',
        'sport 1',
        'zoo',
        'hage',
        'elkjøp',
        'elkjop',
        'power',
        'bente',
        'ark',
        'ideal',
        'sostrene',
        'søstrene',
        'feel',
        'kid',
        'blomster',
        'clas ohlson',
        'lindex',
        'frøken strøken',
        'byggmax',
    ],
    'Underholdning': [
        'gjøvik kino',
        'norsk tipping',
        'totenbadet',
        'fjellhallen',
        'geekevents',
        'sveve',
        'fun padel',
        'padel-senter',
        'mjøsstranda',
        'tikkio',
        'kultur',
        'sound',
        '4sound',
        'maire',
        'garnius',
        'liten',
        'hygge',
        'javel',
        'beach bar',
        'mr vape',
        'prodbygeam',
        'nostalgix',
        'kino',
    ],
    'Gaming': ['steam', 'steam games', 'discord', 'riotgames', 'riot', 'jagex', 'eneba'],
    'Abonnement': [
        'apple',
        'tidalmusic',
        'telenor',
        'splice',
        'claude.ai',
        'anthropic',
        'openai',
        'scrimba',
        'real debrid',
        'suno',
        'elitehosting',
        'agderposten',
        'lyse tele',
        'lennardigi',
        'native ins',
        'netflix',
        'disney plus',
        'storytel',
        'mova as',
        'google',
        'max',
        'disney',
        'mova',
        'disney',
        'prime',
        'snapchat',
    ],
    'Netthandel': [
        'cdon',
        'maxgaming',
        'proshop',
        'helthjem',
        'thomann',
        'xxl',
        'norli',
        'nox padel',
        'matchi',
        'posten norge',
        'sp nox',
        'ups',
    ],
    'Helse': [
        'spesialistsenter',
        'apotek',
        'legevakt',
        'helfo',
        'rtg.polikl',
        'vitus',
        'legesenter',
        'oslo storbylege',
        'farmasiet',
        'evidensia',
        'specsave',
        'sunkost',
        'apotheke',
        'spesialistsenter',
        'poliklinikk',
        'bodypower',
    ],
    'Kosmetikk': [
        'cutters',
        'blivakker',
        'nailster',
        'nordicnails',
        'nordicfeel',
        'kicks',
        'rituals',
        'feel raufoss',
        'zalando',
        'bubbleroom',
        'change lingerie',
        'lyko',
        'gina',
        'kappahl',
        'cosmetics',
        'euro sko',
        'makeup',
        'cubus',
        'vero',
        'atelièr',
        'get inspired',
        'nakd',
        'glitter',
        'skoringen',
        'vita',
        'silver',
        'change',
        'fredrik',
        'junkyard',
        'h&m',
        'nyx',
        'new yorker',
        'kjolesenteret',
        'm.a.p.t',
        'ambrosia',
        'q blush',
        'vic',
        'claire',
    ],
    'Kreditt': ['klarna', 'qliro', 'credicare', 'tfbank', 'riverty', 'arvato'],
    'Transport': ['ruter', 'entur', 'seaways', 'vy app', 'asfinag', 'scandlines', 'mv'],
    'Bil': [
        'uno-x',
        'tesla',
        'ionity',
        'kople',
        'recharge',
        'easypark',
        'onepark',
        'apcoa',
        'nordea finans',
        'naf',
        'thansen',
        'konzum',
        'mer',
        'norges automobil',
        'drivstof',
    ],
    'Bolig': ['nedbetaling'],
    'Boutgifter': [
        'fortum',
        'vestre toten kommune',
        'ringsaker kommune',
        'globalconnect',
        'verisure',
        'omkostninger',
        'minel',
    ],
    'Forsikring': ['fremtind forsikring', 'gjensidige', 'agria'],
    'Overføring': ['betaling', 'overføring', 'kontoregulering', 'revolut', 'adyen', 'vipps'],
    'Inntekt': ['nav', 'skatteetaten', 'lønn', 'ztl payment', 'lena og centrum'],
    'Sparing': ['renter', 'dnb aksje', 'verdipapir', 'dnb global', 'aske'],
    'Diverse': [
        'barnas hus',
        'tugo',
        'stian',
        'finn',
        'total service',
        'avarda',
        'zettr',
        'regnum',
        'grotle',
        'nya',
        'terme',
        'espos',
    ],
    'Annet': [],
};

export const defaultOwnAccounts: string[] = [''];

export const defaultOptions: Omit<Required<Options>, 'extractionRules'> = {
    merchantAliases: defaultMerchantAliases,
    categoryKeywords: defaultCategoryKeywords,
    ownAccounts: defaultOwnAccounts,
    cityPrefixes: defaultCityPrefixes,
    nWordMerchants: defaultNWordMerchants,
    corporateSuffixPattern: defaultCorporateSuffixPattern,
    locale: new Intl.Locale('nb-NO'),
    debug: false,
};
