import type { Category } from "./categories.js";
import type { MerchantAliases, Options, ResolvedOptions } from "./types.js";

export const defaultCorporateSuffixPattern: RegExp =
	/\s+(forsikring(saktiebolaget)?|finans|norge|as|asa)\b.*$/i;

export const defaultCityPrefixes: string[] = [
	"Gjøvik",
	"Raufoss",
	"Lena",
	"Bøverbru",
	"Kapp",
	"Kolbu",
	"Reinsvoll",
	"Moelv",
	"Heidal",
	"Oslo",
];

export const defaultNWordMerchants: Record<string, number> = {
	// 2-word merchants
	Burger: 2,
	Mr: 2,
	New: 2,
	The: 2,
	King: 2,
	Cc: 2,
	Supermarket: 2,
	Crown: 2,
	Caffe: 2,
	Cafe: 2,
	Hotel: 2,
	Aashaug: 2,
	Gina: 2,
	Espresso: 2,
	Apotek: 2,
	Circle: 2,
	Sostrene: 2,
	Søstrene: 2,
	Clas: 2,
	Liten: 2,
	Øya: 2,
	Euro: 2,
	Barnas: 2,
	Get: 2,
	Makeup: 2,
	Vero: 2,
	Coop: 2,
	Bentes: 2,
	Bente: 2,
	EBILLETT: 2,
	Mc: 2,
	Change: 2,
	Waffle: 2,
	Little: 2,
	Dos: 2,
	Real: 2,
	Fly: 2,
	Norsk: 2,
	Beach: 2,
	Total: 2,
	Frøken: 2,
	Mv: 2,
	Q: 2,
	Claire: 2,

	// 3-word merchants
	Salt: 3,
	Deli: 3,
	"Sp ": 3,
	Hage: 3,
	Sander: 3,
};

export const defaultMerchantAliases: MerchantAliases = {
	extra: "Coop Extra",
	"f™rsžkringsaktiebolaget agria": "Agria",
	silogata: "Ukjent",
	mdc: "McDonald's",
	mcdonalds: "McDonald's",
	mcd: "McDonald's",
	"mc donald's": "McDonald's",
	"mc donald": "McDonald's",
	"lyko.com/no": "Lyko",
	"apple.com/bill": "Apple",
	bk: "Burger King",
	tqsr: "Burger King",
	ossg: "Gjøvik Poliklinikk",
	no0770: "H&M",
	no0772: "H&M",
	hm: "H&M",
	berit: "Kjolesenteret Lillo",
	rema: "REMA 1000",
	"uno-x": "Uno-X",
	"steamgames.com": "Steam",
	"clas ohl": "Clas Ohlson",
	bkh: "Bislett Kebab House",
	"sostrene grene": "Søstrene Grene",
	"dfdsseaways.dk": "DFDS",
	"caiacosmetics.no": "Caia Cosmetics",
	"www.silverlines.no": "Silverlines",
	"garnius.no": "Garnius",
	specsave: "Specsavers",
	sound: "4Sound",
	bentes: "Bentes Hjerte",
	"the conjuring": "Kino",
	telenor: "Telenor",
	tfbank: "Avarda",
	"tugo'": "Tugo",
	kfc: "KFC",
	"vinmonopolet.no": "Vinmonopolet",
	"aashaug blomst": "Aashaug Blomster",
	snap: "Snapchat",
	domino: "Dominos",
	"q:blush": "Q Blush",
	vidaxlno: "Vida XL",
	"jemogfix.no": "Jem & Fix",
	"geta bakeripro": "Geta Bakeri",
	nebbenes: "Nebbenes Kro",
	riotgamesl: "Riot Games",
	lennardigit: "Lennar Digital",
	tidalmusica: "Tidal",
	nostalgixa: "Nostalgix Audio",
	"fredrikoglouisia.no": "Fredrik og Louisa",
	"620": "Europris",
	verdipapir: "Verdipapir",
	apotek1: "Apotek 1",
};

export const defaultCategoryKeywords: Record<Category, string[]> = {
	Dagligvare: [
		"extra",
		"kiwi",
		"rema",
		"coop",
		"bunnpris",
		"spar",
		"interspar",
		"supermarket",
		"joker",
		"matkroken",
		"cc mat",
		"mix",
		"vinmonopolet",
		"obs",
		"snarkjøp",
		"lidl",
		"ica",
		"maximat",
		"systembolaget",
		"gottebiten",
		"kaufland",
		"godishuset",
		"plodine",
		"supermerc",
	],
	"Mat ute": [
		"nebbenes kro",
		"ysteri",
		"burger king",
		"mcdonald's",
		"little eat",
		"fly chicken",
		"expressenpizza",
		"pizzabakeren",
		"raufoss pizza",
		"dos amigos",
		"sander asia mat",
		"gelatiamo",
		"thai bahn",
		"wolt",
		"foodora",
		"hygge gjøvik",
		"javel oslo",
		"totensnacks",
		"king kebap",
		"selecta",
		"øya maritim",
		"max burgers",
		"shell",
		"7-eleven",
		"7 eleven",
		"esso",
		"st1",
		"kitch",
		"salt og pepper",
		"salt & pepper",
		"waffle",
		"circle",
		"deli",
		"astral",
		"bkh",
		"slasticarna",
		"tqsr",
		"caffe",
		"yx",
		"bakeri",
		"konoba",
		"kfc",
		"heim",
		"heidi",
		"dominos",
		"olearys",
		"o learys",
		"monky",
		"northland",
		"kebab",
		"crazy foodtruc",
		"cid mat",
		"narvesen",
	],
	Hjem: [
		"feel",
		"jem & fix",
		"interhome",
		"vidaxl",
		"ikea",
		"biltema",
		"rusta",
		"jula",
		"plantasjen",
		"europris",
		"normal",
		"buddy",
		"musti",
		"jysk",
		"nille",
		"sport 1",
		"zoo",
		"hage",
		"elkjøp",
		"elkjop",
		"power",
		"bente",
		"ark",
		"ideal",
		"sostrene",
		"søstrene",
		"kid",
		"blomster",
		"clas ohlson",
		"lindex",
		"frøken strøken",
		"byggmax",
		"vida xl",
	],
	Underholdning: [
		"norsk tipping",
		"totenbadet",
		"fjellhallen",
		"geekevents",
		"sveve",
		"padel",
		"padel-senter",
		"mjøsstranda",
		"tikkio",
		"kultur",
		"sound",
		"4sound",
		"maire",
		"garnius",
		"liten",
		"hygge",
		"javel",
		"beach bar",
		"mr vape",
		"prodbygeam",
		"nostalgix",
		"kino",
		"lennar",
		"photopea.com",
		"hoopla",
		"lucky",
		"bowling",
		"wrightegaarden",
		"grimaas brygg",
		"cafe amsterdam",
	],
	Gaming: ["steam", "riotgames", "riot", "jagex", "eneba"],
	Abonnement: [
		"discord",
		"apple",
		"tidal",
		"telenor",
		"splice",
		"claude.ai",
		"anthropic",
		"openai",
		"scrimba",
		"real debrid",
		"suno",
		"elitehosting",
		"agderposten",
		"lyse tele",
		"native ins",
		"netflix",
		"storytel",
		"google",
		"max",
		"disney",
		"mova",
		"prime",
		"snapchat",
	],
	Netthandel: [
		"cdon",
		"maxgaming",
		"proshop",
		"helthjem",
		"thomann",
		"xxl",
		"norli",
		"nox padel",
		"matchi",
		"posten norge",
		"sp nox",
		"ups",
	],
	Helse: [
		"spesialistsenter",
		"apotek",
		"apoteket",
		"legevakt",
		"helfo",
		"rtg.polikl",
		"vitus",
		"legesenter",
		"oslo storbylege",
		"farmasiet",
		"evidensia",
		"specsave",
		"sunkost",
		"apotheke",
		"poliklinikk",
		"bodypower",
	],
	Kosmetikk: [
		"cutters",
		"blivakker",
		"nailster",
		"nordicnails",
		"nordicfeel",
		"kicks",
		"rituals",
		"lyko",
		"cosmetics",
		"makeup",
		"vero",
		"atelièr",
		"glitter",
		"vita",
		"silver",
		"change",
		"fredrik og louisa",
		"nyx",
		"q blush",
		"claire",
	],
	Klær: [
		"zalando",
		"bubbleroom",
		"change lingerie",
		"gina",
		"kappahl",
		"h&m",
		"nakd",
		"get inspired",
		"ambrosia",
		"junkyard",
		"new yorker",
		"kjolesenteret",
		"vic",
		"euro sko",
		"m.a.p.t",
		"cubus",
		"skoringen",
		"lefties",
	],
	Kreditt: ["klarna", "qliro", "credicare", "tfbank", "riverty", "arvato"],
	Transport: [
		"ruter",
		"entur",
		"seaways",
		"vy app",
		"asfinag",
		"scandlines",
		"mv",
		"airshoppen",
		"parking",
	],
	Bil: [
		"uno-x",
		"tesla",
		"ionity",
		"kople",
		"recharge",
		"easypark",
		"onepark",
		"apcoa",
		"nordea finans",
		"naf",
		"thansen",
		"konzum",
		"mer",
		"norges automobil",
		"drivstof",
	],
	Bolig: ["nedbetaling"],
	Boutgifter: [
		"fortum",
		"vestre toten kommune",
		"ringsaker kommune",
		"globalconnect",
		"verisure",
		"omkostninger",
		"minel",
	],
	Forsikring: ["fremtind forsikring", "gjensidige", "agria"],
	Overføring: [
		"betaling",
		"overføring",
		"kontoregulering",
		"revolut",
		"adyen",
		"vipps",
		"svea",
	],
	Inntekt: ["nav", "skatte", "lønn", "ztl payment", "lena og centrum"],
	Sparing: ["renter", "dnb aksje", "verdipapir", "dnb global", "aske"],
	Diverse: [
		"barnas hus",
		"tugo",
		"stian",
		"finn",
		"total service",
		"avarda",
		"zettr",
		"regnum",
		"grotle",
		"nya",
		"terme",
		"espos",
		"hotel laimerhof",
		"duty-free",
		"stadio",
		"real-debrid",
	],
	Annet: [],
};

export const defaultOptions: ResolvedOptions = {
	merchantAliases: defaultMerchantAliases,
	categoryKeywords: defaultCategoryKeywords,
	ownAccounts: [],
	cityPrefixes: defaultCityPrefixes,
	nWordMerchants: defaultNWordMerchants,
	corporateSuffixPattern: defaultCorporateSuffixPattern,
	debug: false,
};

/** Merge user options over the defaults, ignoring explicitly `undefined` values. */
export function resolveOptions(options: Options = {}): ResolvedOptions {
	const provided = Object.fromEntries(
		Object.entries(options).filter(([, value]) => value !== undefined),
	) as Options;

	return { ...defaultOptions, ...provided };
}
